server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  application:
    name: azure-private-link-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
